// GEN-001: Format Test
// Description: undefined
// Priority: Medium
// Tags: recorded
// Generated by Test Recorder: GEN-001-1751520590215

import type { TestCase } from 'endorphin-ai';

const recordedTest: TestCase = {
  id: 'GEN-001',
  name: 'Format Test',
  description: 'undefined',
  priority: 'Medium',
  tags: [
  "recorded"
],
  data: async () => {
    console.log('Using recorded test data...');
    return     {
          "key": "value",
          "user": "test"
    };
  },

  task: async (data, setupData) => {
    return `
      STEP 1: Test step
      STEP 2: Verify the test completed successfully
    `;
  },
  // Recording metadata
  recordingId: 'GEN-001-1751520590215',
  recordedSteps: 1
};

export default recordedTest;
