// ere: erer
// Description: er
// Priority: Medium
// Tags: recorded
// Generated by Test Recorder: ere-1751065519097

import type { TestCase } from 'endorphin-ai';

export const ere: TestCase = {
  "id": "ere",
  "name": "erer",
  "description": "er",
  "priority": "Medium",
  "tags": [
    "recorded"
],
  "site": "https://qafromla.herokuapp.com/",
  "testData": {},
  "task": "Navigate to https://qafromla.herokuapp.com/ click on login button STOP - test completed.",
  "recordingId": "ere-1751065519097",
  "recordedSteps": 2
};
